version: '3'

services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1q2w3e4R5t#"
      MYSQL_DATABASE: "noala"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1q2w3e4R5t#"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
      
    volumes:
      - ./database/data/mysql:/bitnami/mysql/data
    networks:
      - backend

networks:
  backend:
    external: true